server:
  port: 8080
  servlet:
    context-path: /vision/
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.117.113:3306/visiondb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: sa

#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.vision.pojo.*    #别名包
  mapper-locations: classpath:/mybatis/mappers/*/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true